### ISSUE TITLE
PA Review: Tracks

### ISSUE THREAD

**Issue by Mpompili** [Mpompili/vibesky#4]
- [x]  Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
Great job! We fixed one of the issues with an early return with a `Loading` div prior to the track information being received in the state. We also styled the comment form in the index and track page. 

- [x] Using the lifecycle method `componentWillReceiveProps` and `componentWillMount` such that a user can navigate between tracks and the track show component.

**Comment by anastassia-b** [comment]
Sweet. Only a few things to complete this MVP: 

- [x] Check that a user can upload a track via heroku. It doesn't work for me, I get a `500 Server Error`.
- [x] Make the entire track image a link to the track page. It will be easier to navigate via, instead of clicking the track name, which is really small.

**Comment by Mpompili** [comment]
@anastassia-b done :]

**Comment by anastassia-b** [comment]
Excellent, I was able to upload a song and everything works! This MVP is complete!
